[string[]] $knownEnvVars = @(
    "UNICORN_LAB_INIT_SCRIPT_BRANCH",
    "UNICORN_LAB_GUIDE_URL", "UNICORN_LAB_SAMPLE_APP_GIT_REPO_URL", "UNICORN_LAB_SAMPLE_APP_GIT_BRANCH", 
    "UNICORN_LAB_SAMPLE_APP_SOLUTION_DIR", "UNICORN_LAB_SAMPLE_APP_SOLUTION_FILE", "UNICORN_LAB_SAMPLE_APP_BUILD_CONFIG",
    "UNICORN_LAB_BOOTSTRAP_CDK", "UNICORN_LAB_SAMPLE_APP_CODECOMMIT_REPO_NAME",
    "UNICORN_LAB_LINUX_DOCKER_START", "UNICORN_LAB_LINUX_DOCKER_AMI", "UNICORN_LAB_LINUX_DOCKER_INSTANCE_SIZE",
    "UNICORN_LAB_AWS_RIP_ECR", "UNICORN_LAB_AWS_RIP_CFNS", "UNICORN_LAB_RESERVED_1",
    "UNICORN_LAB_USER_SCRIPT_GIT_URL", "UNICORN_LAB_USER_SCRIPT_GIT_BRANCH"
)
